# runs hourly
cleanup_unconfirmed_users:
  cron: "0 * * * *"
  class: "CleanupUnconfirmedUsersJob"
  queue: maintenance
  args:
    - 7

# runs every 10 minutes
cleanup_expired_email_change_requests:
  cron: "*/10 * * * *"
  class: "CleanupExpiredEmailChangeRequestsJob"
  queue: maintenance
